#nullable enable
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using Microsoft.VisualStudio.TestTools.UnitTesting;
using YTray.Core;
using YTray.Models;

namespace YTray.Tests
{
    [TestClass]
    public class BrowserIdentityColorTests
    {
        [DataTestMethod]
        [DataRow("A", 242, 98, 21)]
        [DataRow("B", 37, 99, 235)]
        [DataRow("C", 22, 163, 74)]
        [DataRow("D", 124, 58, 237)]
        [DataRow("E", 190, 24, 93)]
        [DataRow("F", 15, 118, 110)]
        [DataRow("G", 242, 98, 21)]
        [DataRow(" aa ", 22, 163, 74)]
        [DataRow("ZZ", 15, 118, 110)]
        public void PaletteMatchesMacOS(string badge, int r, int g, int b)
        {
            Assert.AreEqual(Color.FromArgb(r, g, b), BrowserIdentityColor.ForBadge(badge));
            Assert.AreEqual($"--install-autogenerated-theme={r},{g},{b}", BrowserIdentityColor.ThemeArgument(badge));
        }

        [TestMethod]
        public void EveryBadgeHasReadableTextAndStableCycle()
        {
            double Luminance(Color c)
            {
                double Linear(byte v) => v / 255d <= 0.04045 ? v / 255d / 12.92 : Math.Pow((v / 255d + 0.055) / 1.055, 2.4);
                return 0.2126 * Linear(c.R) + 0.7152 * Linear(c.G) + 0.0722 * Linear(c.B);
            }
            for (var ordinal = 1; ordinal <= 702; ordinal++)
            {
                var badge = DockBadgeLabel.DefaultLabel(ordinal);
                var background = BrowserIdentityColor.ForBadge(badge);
                var foreground = BrowserIdentityColor.Foreground(badge);
                var a = Luminance(background); var b = Luminance(foreground);
                Assert.IsTrue((Math.Max(a, b) + 0.05) / (Math.Min(a, b) + 0.05) >= 4.5, badge);
                Assert.AreEqual(BrowserIdentityColor.ForBadge(DockBadgeLabel.DefaultLabel((ordinal - 1) % 6 + 1)), background);
            }
            Assert.ThrowsException<YTrayException>(() => BrowserIdentityColor.ForBadge("123"));
        }

        [DataTestMethod]
        [DataRow(LaunchMode.Quick)]
        [DataRow(LaunchMode.Custom)]
        [DataRow(LaunchMode.Isolated)]
        public void ThemesOnlyInitializeNewProfiles(LaunchMode mode)
        {
            var settings = new LaunchSettings();
            List<string> Arguments(bool isNew = true, bool restore = false) => BrowserLauncher.BuildArguments(
                mode, settings, @"C:\YTray\Profiles\test", 9222, new List<BrowserPlugin>(),
                instanceBadge: "D", isNewProfile: isNew, restoreLastSession: restore);
            Assert.AreEqual(1, Arguments().Count(a => a == "--install-autogenerated-theme=124,58,237"));
            Assert.IsFalse(Arguments(false).Any(a => a.StartsWith("--install-autogenerated-theme=")),
                "Restores with proxy-auth bootstrap must also preserve the existing theme.");
            Assert.IsFalse(Arguments(restore: true).Any(a => a.StartsWith("--install-autogenerated-theme=")));
            settings.ColorizeBrowserInstances = false;
            Assert.IsFalse(Arguments().Any(a => a.StartsWith("--install-autogenerated-theme=")));
        }

        [TestMethod]
        public void ThemePreferenceSurvivesCloneAndPersistenceAndDefaultsForOldState()
        {
            var root = Path.Combine(Path.GetTempPath(), "ytray-color-tests-" + Guid.NewGuid());
            try
            {
                Directory.CreateDirectory(root);
                File.WriteAllText(StatePersistence.StatePath(root), "{\"Settings\":{}}");
                Assert.IsTrue(StatePersistence.Load(root)!.Settings.ColorizeBrowserInstances);
                var settings = new LaunchSettings { ColorizeBrowserInstances = false };
                Assert.IsFalse(settings.Clone().ColorizeBrowserInstances);
                using (var store = new InstanceStore(root, false, false))
                {
                    store.Settings.ColorizeBrowserInstances = false;
                    Assert.IsFalse(store.QuickLaunchConfiguration(false)!.ColorizeBrowserInstances);
                    Assert.IsFalse(store.QuickLaunchConfiguration(true)!.ColorizeBrowserInstances);
                }
                StatePersistence.Save(root, new PersistedState { Settings = settings });
                Assert.IsFalse(StatePersistence.Load(root)!.Settings.ColorizeBrowserInstances);
            }
            finally { Directory.Delete(root, true); }
        }

        [TestMethod]
        public void TaskbarFramesContainAllIdentityColorsAndKeepBrowserCornerClear()
        {
            foreach (var badge in new[] { "A", "B", "C", "D", "E", "F", "AA", "ZZ" })
            foreach (var size in new[] { 16, 20, 24, 32, 40, 48, 64, 256 })
            using (var icon = BrowserProcessIcon.RenderIcon(null, badge, size))
            {
                var color = BrowserIdentityColor.ForBadge(badge).ToArgb();
                var colorPixels = 0;
                for (var y = 0; y < size; y++)
                for (var x = 0; x < size; x++)
                    if (icon.GetPixel(x, y).ToArgb() == color) colorPixels++;
                Assert.IsTrue(colorPixels > 0, $"{badge} at {size}px must retain its identity colour");
                Assert.AreEqual(0, icon.GetPixel(size - 1, size - 1).A);
            }
        }

        [TestMethod]
        public void StoppedAndMissingRuntimeProfilesKeepTheirIdentity()
        {
            var instance = new BrowserInstance { DockBadge = "B", Status = InstanceStatus.Stopped };
            var row = new BrowserInstancePresentation(instance);
            Assert.IsNotNull(row.InstanceIconSource);
            Assert.IsTrue(row.IdentityBrush.IsFrozen);
            Assert.AreEqual((byte)37, row.IdentityBrush.Color.R);
            Assert.AreEqual((byte)255, row.IdentityForegroundBrush.Color.R);
            Assert.IsNotNull(new BrowserInstancePresentation(new BrowserInstance()).IdentityBrush);
        }
    }
}
