import AppKit
import Foundation

struct BrowserIdentityColor: Equatable {
    let red: Int
    let green: Int
    let blue: Int

    static let palette = [
        BrowserIdentityColor(red: 242, green: 98, blue: 21),   // A · YTray orange
        BrowserIdentityColor(red: 37, green: 99, blue: 235),   // B · blue
        BrowserIdentityColor(red: 22, green: 163, blue: 74),   // C · green
        BrowserIdentityColor(red: 124, green: 58, blue: 237),  // D · violet
        BrowserIdentityColor(red: 190, green: 24, blue: 93),   // E · magenta
        BrowserIdentityColor(red: 15, green: 118, blue: 110),  // F · teal
    ]

    static func color(for badge: String) -> BrowserIdentityColor {
        let ordinal = badge.uppercased().unicodeScalars.reduce(0) { partial, scalar in
            let letter = max(1, min(26, Int(scalar.value) - 64))
            return partial * 26 + letter
        }
        return palette[(max(1, ordinal) - 1) % palette.count]
    }

    var chromeThemeArgument: String {
        "--install-autogenerated-theme=\(red),\(green),\(blue)"
    }

    var nsColor: NSColor {
        NSColor(
            calibratedRed: CGFloat(red) / 255,
            green: CGFloat(green) / 255,
            blue: CGFloat(blue) / 255,
            alpha: 1
        )
    }
}
