#nullable enable
using System;
using System.Drawing;
using System.Globalization;
using System.Windows.Media;

namespace YTray.Core
{
    /// <summary>Stable profile identity palette shared with macOS BrowserIdentityColor.</summary>
    public static class BrowserIdentityColor
    {
        private static readonly System.Drawing.Color[] Palette =
        {
            System.Drawing.Color.FromArgb(242, 98, 21),
            System.Drawing.Color.FromArgb(37, 99, 235),
            System.Drawing.Color.FromArgb(22, 163, 74),
            System.Drawing.Color.FromArgb(124, 58, 237),
            System.Drawing.Color.FromArgb(190, 24, 93),
            System.Drawing.Color.FromArgb(15, 118, 110),
        };

        public static System.Drawing.Color ForBadge(string badge)
        {
            var label = DockBadgeLabel.Normalize(badge);
            var ordinal = 0;
            foreach (var letter in label) ordinal = ordinal * 26 + letter - 'A' + 1;
            return Palette[(ordinal - 1) % Palette.Length];
        }

        public static string ThemeArgument(string badge)
        {
            var color = ForBadge(badge);
            return string.Format(CultureInfo.InvariantCulture,
                "--install-autogenerated-theme={0},{1},{2}", color.R, color.G, color.B);
        }

        // Choose the higher-contrast label colour (at least 4.5:1 across this palette).
        // Orange/green need dark text; blue/violet/magenta/teal need white text.
        public static System.Drawing.Color Foreground(string badge)
        {
            var color = ForBadge(badge);
            double Linear(byte component)
            {
                var value = component / 255d;
                return value <= 0.04045 ? value / 12.92 : Math.Pow((value + 0.055) / 1.055, 2.4);
            }
            var luminance = 0.2126 * Linear(color.R) + 0.7152 * Linear(color.G) + 0.0722 * Linear(color.B);
            return luminance > 0.179 ? System.Drawing.Color.Black : System.Drawing.Color.White;
        }

        public static SolidColorBrush Brush(string? badge, bool foreground = false)
        {
            System.Drawing.Color color;
            try { color = foreground ? Foreground(badge!) : ForBadge(badge!); }
            catch (ArgumentException) { color = foreground ? System.Drawing.Color.Black : Palette[0]; }
            catch (Models.YTrayException) { color = foreground ? System.Drawing.Color.Black : Palette[0]; }
            var brush = new SolidColorBrush(System.Windows.Media.Color.FromRgb(color.R, color.G, color.B));
            brush.Freeze();
            return brush;
        }
    }
}
