#nullable enable
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Drawing;
using System.Drawing.Imaging;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using YTray.Models;
using YTray.Native;

namespace YTray.Core
{
    /// <summary>Opt-in real-browser verification using fresh, isolated profiles only.</summary>
    internal static class IdentitySmokeService
    {
        [StructLayout(LayoutKind.Sequential)]
        private struct NativeRect { public int Left, Top, Right, Bottom; }
        [DllImport("user32.dll")] private static extern bool GetWindowRect(IntPtr window, out NativeRect rect);
        [DllImport("user32.dll")] private static extern bool PrintWindow(IntPtr window, IntPtr dc, uint flags);

        internal static async Task RunAsync(string executable, string output)
        {
            output = Path.GetFullPath(output);
            Directory.CreateDirectory(output);
            var scratch = Path.Combine(output, "profiles-" + Guid.NewGuid().ToString("N"));
            var runtime = new BrowserRuntime
            {
                Name = "Identity smoke", ExecutablePath = executable, Version = "local",
                Source = RuntimeSource.Local, BrowserKind = BrowserKind.Chrome,
            };
            var results = new List<object>();
            foreach (var badge in new[] { "A", "B", "C", "D" })
            {
                BrowserLauncher.LaunchResult? launch = null;
                try
                {
                    var settings = new LaunchSettings
                    {
                        HomeURL = "data:text/html," + Uri.EscapeDataString("<title>YTray Identity " + badge + "</title><h1>Profile " + badge + "</h1>"),
                        DebugPort = 19777, IgnoreCertificateErrors = false,
                    };
                    launch = BrowserLauncher.Launch(runtime, LaunchMode.Isolated, settings,
                        new List<BrowserPlugin>(), scratch, 1, badge);
                    var window = await VerifyWindowAsync(launch, badge);
                    var screenshot = await ScreenshotService.CaptureAsync(launch.Instance.DebugPort,
                        launch.Instance.Id, Path.Combine(output, "pages"));
                    CaptureBrowserWindow(window, Path.Combine(output, badge + "-browser.png"));
                    var history = launch.Instance;
                    await CloseAsync(launch);
                    launch.Dispose(); launch = null;
                    var preferencesPath = Path.Combine(history.ProfilePath, "Default", "Preferences");
                    var preferences = JObject.Parse(File.ReadAllText(preferencesPath));
                    var theme = preferences["autogenerated"]?["theme"]?["color"]?.Value<int>();
                    if (theme != BrowserIdentityColor.ForBadge(badge).ToArgb())
                        throw new InvalidOperationException(badge + ": Chrome did not persist the expected identity color.");

                    // Model a later appearance choice in this test-owned profile, then verify
                    // normal restoration does not reinstall the badge's original color.
                    var customColor = BrowserIdentityColor.ForBadge("F").ToArgb();
                    preferences["autogenerated"]!["theme"]!["color"] = customColor;
                    File.WriteAllText(preferencesPath, preferences.ToString(Formatting.None));
                    var customSettings = settings.Clone();
                    launch = BrowserLauncher.Launch(runtime, LaunchMode.Isolated, customSettings,
                        new List<BrowserPlugin>(), scratch, 1, badge, restoring: history);
                    await VerifyWindowAsync(launch, badge);
                    if (launch.Process.StartInfo.Arguments.Contains("--install-autogenerated-theme="))
                        throw new InvalidOperationException(badge + ": restore overwrites the profile theme.");
                    await CloseAsync(launch);
                    var restored = JObject.Parse(File.ReadAllText(preferencesPath))["autogenerated"]?["theme"]?["color"]?.Value<int>();
                    if (restored != customColor)
                        throw new InvalidOperationException(badge + ": persisted theme changed on restore.");
                    results.Add(new { badge, theme, customColor, aumid = history.AppUserModelId, screenshot, restored = true });
                    File.WriteAllText(Path.Combine(output, "identity-smoke.json"), JsonConvert.SerializeObject(results, Formatting.Indented));
                }
                finally
                {
                    if (launch != null)
                    {
                        try { await CloseAsync(launch); } finally { launch.Dispose(); }
                    }
                }
            }
            File.WriteAllText(Path.Combine(output, "smoke-complete.txt"), "A/B/C/D: CDP, taskbar AUMID/icon, theme persistence and restore passed.");
        }

        private static async Task<IntPtr> VerifyWindowAsync(BrowserLauncher.LaunchResult launch, string badge)
        {
            if (!await ScreenshotService.WaitUntilReadyAsync(launch.Instance.DebugPort, 60))
                throw new InvalidOperationException(badge + ": debugger not ready.");
            var expected = AumidResolver.BuildInstanceAumid(BrowserKind.Chrome, badge, launch.Instance.Id);
            var started = Stopwatch.StartNew();
            IntPtr window = IntPtr.Zero;
            while (started.Elapsed < TimeSpan.FromSeconds(20))
            {
                window = WindowEnum.FindFirstVisibleWindow(launch.Instance.ProcessID);
                if (window != IntPtr.Zero && Win32.GetWindowAumid(window) == expected) break;
                await Task.Delay(100);
            }
            if (window == IntPtr.Zero || Win32.GetWindowAumid(window) != expected)
                throw new InvalidOperationException(badge + ": taskbar identity did not stabilize.");
            // Chromium can leave WM_GETICON empty; Explorer uses RelaunchIconResource for
            // these independently grouped buttons. Verify the actual shell property, not a
            // fallback WM_SETICON that would mask a controller regression.
            var iid = Win32.IID_IPropertyStore;
            IPropertyStore properties;
            Marshal.ThrowExceptionForHR(Win32.SHGetPropertyStoreForWindow(window, ref iid, out properties));
            try
            {
                using (var value = new PROPVARIANT())
                {
                    var key = Win32.PKEY_AppUserModel_RelaunchIconResource;
                    properties.GetValue(ref key, value);
                    var resource = value.AsString();
                    if (string.IsNullOrEmpty(resource) || !resource!.EndsWith(launch.Instance.Id + ".ico,0", StringComparison.OrdinalIgnoreCase)
                        || !File.Exists(resource.Substring(0, resource.Length - 2)))
                        throw new InvalidOperationException(badge + ": generated taskbar icon resource missing.");
                }
            }
            finally { Marshal.ReleaseComObject(properties); }
            var title = await ScreenshotService.CurrentPageTitleAsync(launch.Instance.DebugPort, 20);
            if (title != "YTray Identity " + badge) throw new InvalidOperationException(badge + ": page title mismatch: " + title);
            return window;
        }

        private static async Task CloseAsync(BrowserLauncher.LaunchResult launch)
        {
            if (launch.Process.HasExited) return;
            launch.Process.CloseMainWindow();
            for (var attempt = 0; attempt < 60 && !launch.Process.HasExited; attempt++) await Task.Delay(100);
            if (!launch.Process.HasExited)
            {
                launch.Process.Kill();
                launch.Process.WaitForExit(5000);
                throw new InvalidOperationException("Browser did not close cleanly; theme persistence cannot be verified.");
            }
        }

        private static void CaptureBrowserWindow(IntPtr window, string path)
        {
            if (!GetWindowRect(window, out var rect)) throw new InvalidOperationException("Browser window bounds unavailable.");
            using (var image = new Bitmap(rect.Right - rect.Left, rect.Bottom - rect.Top))
            using (var graphics = Graphics.FromImage(image))
            {
                var dc = graphics.GetHdc();
                try { if (!PrintWindow(window, dc, 2)) throw new InvalidOperationException("Browser window capture failed."); }
                finally { graphics.ReleaseHdc(dc); }
                image.Save(path, ImageFormat.Png);
            }
        }
    }
}
